### ISSUE TITLE
Newest Twitter API 1.1 need authentication

### ISSUE THREAD

**Issue by rmutia** [nopper/twittomatic#1]
Latest version of twittomatic still only work for Twitter API v1. All access to Twitter API 1.1 need authentication first so this twittomatic didn't work and TWITTER URL settings need updated to newest Twitter URL

**Comment by nopper** [comment]
It's a known problem and it requires a huge refactoring of the existing code base. I am currently working on a new release which should be open sourced in the near future that handle the new OAuth scheme.
